/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-live-bag-play-filled-16-colored"><circle cx="8" cy="8" r="8" fill="#fff" fill-opacity=".88"/><path d="M8 3.005c.705 0 1.32.48 1.491 1.163l.335 1.337h2.038a.51.51 0 0 1 .511.51v3.813a2.552 2.552 0 0 1-2.552 2.552H6.177a2.552 2.552 0 0 1-2.552-2.552V6.016c0-.282.229-.511.51-.511h2.039l.336-1.337A1.537 1.537 0 0 1 8 3.005ZM4.562 9.828c0 .892.723 1.614 1.615 1.614h3.646c.892 0 1.614-.722 1.614-1.614V6.442h-1.375l.112.449a.47.47 0 0 1-.91.228l-.17-.677H6.907l-.17.677a.47.47 0 0 1-.91-.228l.112-.449H4.563v3.386Zm3.025-2.185.098.042 1.544.932a.38.38 0 0 1 0 .65l-1.544.932a.38.38 0 0 1-.577-.325V8.011a.38.38 0 0 1 .479-.368ZM8 3.943a.6.6 0 0 0-.581.453l-.278 1.109h1.718l-.277-1.109A.6.6 0 0 0 8 3.942Z" fill="#191919"/></symbol>`;

export const EbayIconLiveBagPlayFilled16Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="liveBagPlayFilled16Colored" __type="icon" __symbol={SYMBOL} />
);