/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-live-bag-filled-24"><path d="M12 0a3.517 3.517 0 0 1 3.426 2.723L16.186 6H20.9A1.1 1.1 0 0 1 22 7.1V16a6 6 0 0 1-6 6H8a6 6 0 0 1-6-6V7.1A1.1 1.1 0 0 1 3.1 6h4.713l.761-3.277A3.517 3.517 0 0 1 12 0Zm-.875 10.923a.912.912 0 0 0-1.267.84v4.473a.912.912 0 0 0 1.383.782l3.706-2.238a.912.912 0 0 0 0-1.561l-3.706-2.237-.116-.06ZM12 2c-.706 0-1.318.487-1.477 1.174L9.867 6h4.266l-.655-2.826A1.517 1.517 0 0 0 12 2Z"/></symbol>`;

export const EbayIconLiveBagFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="liveBagFilled24" __type="icon" __symbol={SYMBOL} />
);