/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-ai-search-filled-24"><path d="M10 1a1.5 1.5 0 0 1 0 3 6 6 0 1 0 5.298 8.82 1.5 1.5 0 1 1 2.646 1.412 8.984 8.984 0 0 1-.609.982l5.726 5.725a1.5 1.5 0 1 1-2.122 2.122l-5.726-5.727A9 9 0 1 1 10 1Zm7.125-.293c.202-.943 1.548-.943 1.75 0l.352 1.636a1.864 1.864 0 0 0 1.43 1.43l1.636.352c.943.202.943 1.548 0 1.75l-1.636.352a1.864 1.864 0 0 0-1.43 1.431l-.352 1.635c-.203.943-1.547.943-1.75 0l-.352-1.635a1.865 1.865 0 0 0-1.431-1.431l-1.635-.352c-.943-.202-.943-1.548 0-1.75l1.635-.352a1.864 1.864 0 0 0 1.431-1.43l.352-1.636Z"/></symbol>`;

export const EbayIconAiSearchFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="aiSearchFilled24" __type="icon" __symbol={SYMBOL} />
);